-- Standardized Water Billing Schema (Laravel Conventions)
-- Generated by Antigravity

SET FOREIGN_KEY_CHECKS=0;

-- Drop existing tables (Old Schema)
DROP TABLE IF EXISTS `account_type`, `audit_log`, `barangay`, `billadjustment`, `billadjustmenttype`, `billing_period`, `chargeitem`, `consumer_address`, `customer`, `customercharge`, `customerledger`, `employee`, `ledgersource`, `meter`, `meterassignment`, `meterreading`, `payment`, `paymentallocation`, `permissions`, `position`, `purok`, `reading_zone`, `role_permissions`, `roles`, `serviceapplication`, `serviceconnection`, `statuses`, `system_config`, `user_roles`, `user_types`, `users`, `water_bill`, `water_rates`, `zone_assignment`;

-- Drop existing tables (New Standardized Schema - just in case)
DROP TABLE IF EXISTS `system_configs`, `statuses`, `barangays`, `puroks`, `consumer_addresses`, `user_types`, `users`, `roles`, `permissions`, `permission_role`, `role_user`, `customers`, `account_types`, `reading_zones`, `service_applications`, `service_connections`, `meters`, `meter_assignments`, `positions`, `employees`, `zone_assignments`, `billing_periods`, `meter_readings`, `water_rates`, `water_bills`, `bill_adjustment_types`, `bill_adjustments`, `charge_items`, `customer_charges`, `payments`, `payment_allocations`, `ledger_sources`, `customer_ledgers`, `audit_logs`, `cache`;

-- 1. System Configuration
CREATE TABLE `system_configs` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `key` varchar(100) NOT NULL,
  `value` text,
  `type` enum('string','number','boolean','date','json') NOT NULL DEFAULT 'string',
  `description` text,
  `is_editable` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `system_configs_key_unique` (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Statuses (Lookup Table)
CREATE TABLE `statuses` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `description` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `statuses_name_unique` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Geographic Tables
CREATE TABLE `barangays` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` varchar(10) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `barangays_status_id_foreign` (`status_id`),
  CONSTRAINT `barangays_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `puroks` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` varchar(10) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `barangay_id` bigint(20) UNSIGNED NOT NULL,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `puroks_barangay_id_foreign` (`barangay_id`),
  KEY `puroks_status_id_foreign` (`status_id`),
  CONSTRAINT `puroks_barangay_id_foreign` FOREIGN KEY (`barangay_id`) REFERENCES `barangays` (`id`),
  CONSTRAINT `puroks_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `consumer_addresses` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `house_number` varchar(50) DEFAULT NULL,
  `street_name` varchar(100) DEFAULT NULL,
  `subdivision_name` varchar(100) DEFAULT NULL,
  `barangay_id` bigint(20) UNSIGNED NOT NULL,
  `purok_id` bigint(20) UNSIGNED DEFAULT NULL,
  `landmark` text,
  `zip_code` varchar(10) DEFAULT NULL,
  `latitude` decimal(10,8) DEFAULT NULL,
  `longitude` decimal(11,8) DEFAULT NULL,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `consumer_addresses_barangay_id_foreign` (`barangay_id`),
  KEY `consumer_addresses_purok_id_foreign` (`purok_id`),
  KEY `consumer_addresses_status_id_foreign` (`status_id`),
  CONSTRAINT `consumer_addresses_barangay_id_foreign` FOREIGN KEY (`barangay_id`) REFERENCES `barangays` (`id`),
  CONSTRAINT `consumer_addresses_purok_id_foreign` FOREIGN KEY (`purok_id`) REFERENCES `puroks` (`id`),
  CONSTRAINT `consumer_addresses_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. User Management (RBAC)
CREATE TABLE `user_types` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` varchar(20) NOT NULL,
  `name` varchar(50) NOT NULL,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_types_code_unique` (`code`),
  KEY `user_types_status_id_foreign` (`status_id`),
  CONSTRAINT `user_types_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `users` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(100) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `user_type_id` bigint(20) UNSIGNED DEFAULT NULL,
  `last_login_at` timestamp NULL DEFAULT NULL,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_username_unique` (`username`),
  UNIQUE KEY `users_email_unique` (`email`),
  KEY `users_user_type_id_foreign` (`user_type_id`),
  KEY `users_status_id_foreign` (`status_id`),
  CONSTRAINT `users_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`),
  CONSTRAINT `users_user_type_id_foreign` FOREIGN KEY (`user_type_id`) REFERENCES `user_types` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `roles` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` varchar(50) NOT NULL,
  `name` varchar(100) NOT NULL,
  `description` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `roles_code_unique` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `permissions` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` varchar(50) NOT NULL,
  `name` varchar(100) NOT NULL,
  `description` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `permissions_code_unique` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `permission_role` (
  `role_id` bigint(20) UNSIGNED NOT NULL,
  `permission_id` bigint(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`role_id`,`permission_id`),
  KEY `permission_role_permission_id_foreign` (`permission_id`),
  CONSTRAINT `permission_role_permission_id_foreign` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `permission_role_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `role_user` (
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `role_id` bigint(20) UNSIGNED NOT NULL,
  `assigned_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`,`role_id`),
  KEY `role_user_role_id_foreign` (`role_id`),
  CONSTRAINT `role_user_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `role_user_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. Customer Management
CREATE TABLE `customers` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` varchar(100) NOT NULL,
  `middle_name` varchar(100) DEFAULT NULL,
  `last_name` varchar(100) NOT NULL,
  `contact_number` varchar(20) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `billing_address_id` bigint(20) UNSIGNED DEFAULT NULL,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  `user_id` bigint(20) UNSIGNED DEFAULT NULL COMMENT 'User who created this record',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `customers_billing_address_id_foreign` (`billing_address_id`),
  KEY `customers_status_id_foreign` (`status_id`),
  KEY `customers_user_id_foreign` (`user_id`),
  CONSTRAINT `customers_billing_address_id_foreign` FOREIGN KEY (`billing_address_id`) REFERENCES `consumer_addresses` (`id`),
  CONSTRAINT `customers_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`),
  CONSTRAINT `customers_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `account_types` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` varchar(20) NOT NULL,
  `name` varchar(50) NOT NULL,
  `rate_category` varchar(50) NOT NULL DEFAULT 'residential',
  `description` text,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `account_types_code_unique` (`code`),
  KEY `account_types_status_id_foreign` (`status_id`),
  CONSTRAINT `account_types_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. Service Management
CREATE TABLE `reading_zones` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` varchar(20) NOT NULL,
  `name` varchar(100) NOT NULL,
  `description` text,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `reading_zones_code_unique` (`code`),
  KEY `reading_zones_status_id_foreign` (`status_id`),
  CONSTRAINT `reading_zones_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `service_applications` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` bigint(20) UNSIGNED NOT NULL,
  `service_address_id` bigint(20) UNSIGNED NOT NULL,
  `account_type_id` bigint(20) UNSIGNED NOT NULL,
  `zone_id` bigint(20) UNSIGNED NOT NULL,
  `submitted_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_printed` tinyint(1) NOT NULL DEFAULT 0,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `service_applications_customer_id_foreign` (`customer_id`),
  KEY `service_applications_service_address_id_foreign` (`service_address_id`),
  KEY `service_applications_account_type_id_foreign` (`account_type_id`),
  KEY `service_applications_zone_id_foreign` (`zone_id`),
  KEY `service_applications_status_id_foreign` (`status_id`),
  CONSTRAINT `service_applications_account_type_id_foreign` FOREIGN KEY (`account_type_id`) REFERENCES `account_types` (`id`),
  CONSTRAINT `service_applications_customer_id_foreign` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`),
  CONSTRAINT `service_applications_service_address_id_foreign` FOREIGN KEY (`service_address_id`) REFERENCES `consumer_addresses` (`id`),
  CONSTRAINT `service_applications_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`),
  CONSTRAINT `service_applications_zone_id_foreign` FOREIGN KEY (`zone_id`) REFERENCES `reading_zones` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `service_connections` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_number` varchar(30) NOT NULL,
  `application_id` bigint(20) UNSIGNED DEFAULT NULL,
  `customer_id` bigint(20) UNSIGNED NOT NULL,
  `service_address_id` bigint(20) UNSIGNED NOT NULL,
  `account_type_id` bigint(20) UNSIGNED NOT NULL,
  `zone_id` bigint(20) UNSIGNED NOT NULL,
  `started_at` date NOT NULL,
  `ended_at` date DEFAULT NULL,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `service_connections_account_number_unique` (`account_number`),
  KEY `service_connections_application_id_foreign` (`application_id`),
  KEY `service_connections_customer_id_foreign` (`customer_id`),
  KEY `service_connections_service_address_id_foreign` (`service_address_id`),
  KEY `service_connections_account_type_id_foreign` (`account_type_id`),
  KEY `service_connections_zone_id_foreign` (`zone_id`),
  KEY `service_connections_status_id_foreign` (`status_id`),
  CONSTRAINT `service_connections_account_type_id_foreign` FOREIGN KEY (`account_type_id`) REFERENCES `account_types` (`id`),
  CONSTRAINT `service_connections_application_id_foreign` FOREIGN KEY (`application_id`) REFERENCES `service_applications` (`id`),
  CONSTRAINT `service_connections_customer_id_foreign` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`),
  CONSTRAINT `service_connections_service_address_id_foreign` FOREIGN KEY (`service_address_id`) REFERENCES `consumer_addresses` (`id`),
  CONSTRAINT `service_connections_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`),
  CONSTRAINT `service_connections_zone_id_foreign` FOREIGN KEY (`zone_id`) REFERENCES `reading_zones` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. Meter Management
CREATE TABLE `meters` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `serial_number` varchar(50) NOT NULL,
  `brand` varchar(50) DEFAULT NULL,
  `size` varchar(20) DEFAULT NULL,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `meters_serial_number_unique` (`serial_number`),
  KEY `meters_status_id_foreign` (`status_id`),
  CONSTRAINT `meters_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `meter_assignments` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `connection_id` bigint(20) UNSIGNED NOT NULL,
  `meter_id` bigint(20) UNSIGNED NOT NULL,
  `installed_at` date NOT NULL,
  `removed_at` date DEFAULT NULL,
  `install_reading` decimal(10,3) NOT NULL DEFAULT 0.000,
  `removal_reading` decimal(10,3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `meter_assignments_connection_id_foreign` (`connection_id`),
  KEY `meter_assignments_meter_id_foreign` (`meter_id`),
  CONSTRAINT `meter_assignments_connection_id_foreign` FOREIGN KEY (`connection_id`) REFERENCES `service_connections` (`id`),
  CONSTRAINT `meter_assignments_meter_id_foreign` FOREIGN KEY (`meter_id`) REFERENCES `meters` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 8. Employee & Zone Assignment
CREATE TABLE `positions` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `description` text,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `positions_status_id_foreign` (`status_id`),
  CONSTRAINT `positions_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `employees` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` varchar(100) NOT NULL,
  `middle_name` varchar(100) DEFAULT NULL,
  `last_name` varchar(100) NOT NULL,
  `position_id` bigint(20) UNSIGNED NOT NULL,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `employees_position_id_foreign` (`position_id`),
  KEY `employees_status_id_foreign` (`status_id`),
  CONSTRAINT `employees_position_id_foreign` FOREIGN KEY (`position_id`) REFERENCES `positions` (`id`),
  CONSTRAINT `employees_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `zone_assignments` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `zone_id` bigint(20) UNSIGNED NOT NULL,
  `employee_id` bigint(20) UNSIGNED NOT NULL,
  `effective_from` date NOT NULL,
  `effective_to` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `zone_assignments_zone_id_foreign` (`zone_id`),
  KEY `zone_assignments_employee_id_foreign` (`employee_id`),
  CONSTRAINT `zone_assignments_employee_id_foreign` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`),
  CONSTRAINT `zone_assignments_zone_id_foreign` FOREIGN KEY (`zone_id`) REFERENCES `reading_zones` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 9. Billing & Readings
CREATE TABLE `billing_periods` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `year` int(11) NOT NULL,
  `month` int(11) NOT NULL,
  `code` varchar(20) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `reading_deadline` date DEFAULT NULL,
  `billing_date` date DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `billing_periods_code_unique` (`code`),
  KEY `billing_periods_status_id_foreign` (`status_id`),
  CONSTRAINT `billing_periods_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `meter_readings` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `meter_assignment_id` bigint(20) UNSIGNED NOT NULL,
  `billing_period_id` bigint(20) UNSIGNED NOT NULL,
  `reading_date` date NOT NULL,
  `reading_value` decimal(10,3) NOT NULL,
  `previous_reading` decimal(10,3) NOT NULL,
  `consumption` decimal(10,3) GENERATED ALWAYS AS (`reading_value` - `previous_reading`) VIRTUAL,
  `is_estimated` tinyint(1) NOT NULL DEFAULT 0,
  `estimated_reason` varchar(255) DEFAULT NULL,
  `reader_employee_id` bigint(20) UNSIGNED DEFAULT NULL,
  `photo_url` varchar(255) DEFAULT NULL,
  `remarks` text,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `meter_readings_meter_assignment_id_foreign` (`meter_assignment_id`),
  KEY `meter_readings_billing_period_id_foreign` (`billing_period_id`),
  KEY `meter_readings_reader_employee_id_foreign` (`reader_employee_id`),
  CONSTRAINT `meter_readings_billing_period_id_foreign` FOREIGN KEY (`billing_period_id`) REFERENCES `billing_periods` (`id`),
  CONSTRAINT `meter_readings_meter_assignment_id_foreign` FOREIGN KEY (`meter_assignment_id`) REFERENCES `meter_assignments` (`id`),
  CONSTRAINT `meter_readings_reader_employee_id_foreign` FOREIGN KEY (`reader_employee_id`) REFERENCES `employees` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `water_rates` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_type_id` bigint(20) UNSIGNED NOT NULL,
  `billing_period_id` bigint(20) UNSIGNED NOT NULL,
  `min_range` int(11) NOT NULL DEFAULT 0,
  `max_range` int(11) NOT NULL,
  `rate_value` decimal(10,2) NOT NULL,
  `rate_increment` decimal(10,2) NOT NULL DEFAULT 0.00,
  `effective_from` date NOT NULL,
  `effective_to` date DEFAULT NULL,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  `user_id` bigint(20) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `water_rates_account_type_id_foreign` (`account_type_id`),
  KEY `water_rates_billing_period_id_foreign` (`billing_period_id`),
  KEY `water_rates_status_id_foreign` (`status_id`),
  KEY `water_rates_user_id_foreign` (`user_id`),
  CONSTRAINT `water_rates_account_type_id_foreign` FOREIGN KEY (`account_type_id`) REFERENCES `account_types` (`id`),
  CONSTRAINT `water_rates_billing_period_id_foreign` FOREIGN KEY (`billing_period_id`) REFERENCES `billing_periods` (`id`),
  CONSTRAINT `water_rates_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`),
  CONSTRAINT `water_rates_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `water_bills` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `connection_id` bigint(20) UNSIGNED NOT NULL,
  `billing_period_id` bigint(20) UNSIGNED NOT NULL,
  `previous_reading_id` bigint(20) UNSIGNED DEFAULT NULL,
  `current_reading_id` bigint(20) UNSIGNED NOT NULL,
  `consumption` decimal(10,3) NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `due_date` date NOT NULL,
  `adjustment_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_amount` decimal(12,2) GENERATED ALWAYS AS (`amount` + `adjustment_amount`) VIRTUAL,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `water_bills_connection_id_foreign` (`connection_id`),
  KEY `water_bills_billing_period_id_foreign` (`billing_period_id`),
  KEY `water_bills_previous_reading_id_foreign` (`previous_reading_id`),
  KEY `water_bills_current_reading_id_foreign` (`current_reading_id`),
  KEY `water_bills_status_id_foreign` (`status_id`),
  CONSTRAINT `water_bills_billing_period_id_foreign` FOREIGN KEY (`billing_period_id`) REFERENCES `billing_periods` (`id`),
  CONSTRAINT `water_bills_connection_id_foreign` FOREIGN KEY (`connection_id`) REFERENCES `service_connections` (`id`),
  CONSTRAINT `water_bills_current_reading_id_foreign` FOREIGN KEY (`current_reading_id`) REFERENCES `meter_readings` (`id`),
  CONSTRAINT `water_bills_previous_reading_id_foreign` FOREIGN KEY (`previous_reading_id`) REFERENCES `meter_readings` (`id`),
  CONSTRAINT `water_bills_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 10. Adjustments & Charges
CREATE TABLE `bill_adjustment_types` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `direction` enum('credit','debit') NOT NULL,
  `description` text,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `bill_adjustment_types_status_id_foreign` (`status_id`),
  CONSTRAINT `bill_adjustment_types_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `bill_adjustments` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `bill_id` bigint(20) UNSIGNED NOT NULL,
  `adjustment_type_id` bigint(20) UNSIGNED NOT NULL,
  `old_reading` decimal(10,3) DEFAULT NULL,
  `new_reading` decimal(10,3) DEFAULT NULL,
  `amount` decimal(12,2) NOT NULL,
  `remarks` text,
  `user_id` bigint(20) UNSIGNED DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `bill_adjustments_bill_id_foreign` (`bill_id`),
  KEY `bill_adjustments_adjustment_type_id_foreign` (`adjustment_type_id`),
  KEY `bill_adjustments_user_id_foreign` (`user_id`),
  CONSTRAINT `bill_adjustments_adjustment_type_id_foreign` FOREIGN KEY (`adjustment_type_id`) REFERENCES `bill_adjustment_types` (`id`),
  CONSTRAINT `bill_adjustments_bill_id_foreign` FOREIGN KEY (`bill_id`) REFERENCES `water_bills` (`id`),
  CONSTRAINT `bill_adjustments_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `charge_items` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` varchar(20) NOT NULL,
  `name` varchar(100) NOT NULL,
  `default_amount` decimal(12,2) DEFAULT NULL,
  `description` text,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `charge_items_code_unique` (`code`),
  KEY `charge_items_status_id_foreign` (`status_id`),
  CONSTRAINT `charge_items_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `customer_charges` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` bigint(20) UNSIGNED NOT NULL,
  `application_id` bigint(20) UNSIGNED DEFAULT NULL,
  `connection_id` bigint(20) UNSIGNED DEFAULT NULL,
  `charge_item_id` bigint(20) UNSIGNED NOT NULL,
  `quantity` decimal(10,3) NOT NULL DEFAULT 1.000,
  `amount` decimal(12,2) NOT NULL,
  `due_date` date DEFAULT NULL,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `customer_charges_customer_id_foreign` (`customer_id`),
  KEY `customer_charges_application_id_foreign` (`application_id`),
  KEY `customer_charges_connection_id_foreign` (`connection_id`),
  KEY `customer_charges_charge_item_id_foreign` (`charge_item_id`),
  KEY `customer_charges_status_id_foreign` (`status_id`),
  CONSTRAINT `customer_charges_application_id_foreign` FOREIGN KEY (`application_id`) REFERENCES `service_applications` (`id`),
  CONSTRAINT `customer_charges_charge_item_id_foreign` FOREIGN KEY (`charge_item_id`) REFERENCES `charge_items` (`id`),
  CONSTRAINT `customer_charges_connection_id_foreign` FOREIGN KEY (`connection_id`) REFERENCES `service_connections` (`id`),
  CONSTRAINT `customer_charges_customer_id_foreign` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`),
  CONSTRAINT `customer_charges_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 11. Payments & Ledger
CREATE TABLE `payments` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `receipt_number` varchar(50) NOT NULL,
  `customer_id` bigint(20) UNSIGNED NOT NULL,
  `payment_date` date NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `method` enum('cash','check','online') NOT NULL DEFAULT 'cash',
  `reference_number` varchar(100) DEFAULT NULL,
  `user_id` bigint(20) UNSIGNED DEFAULT NULL,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `payments_receipt_number_unique` (`receipt_number`),
  KEY `payments_customer_id_foreign` (`customer_id`),
  KEY `payments_user_id_foreign` (`user_id`),
  KEY `payments_status_id_foreign` (`status_id`),
  CONSTRAINT `payments_customer_id_foreign` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`),
  CONSTRAINT `payments_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`),
  CONSTRAINT `payments_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payment_allocations` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `payment_id` bigint(20) UNSIGNED NOT NULL,
  `bill_id` bigint(20) UNSIGNED DEFAULT NULL,
  `charge_id` bigint(20) UNSIGNED DEFAULT NULL,
  `amount` decimal(12,2) NOT NULL,
  `type` enum('bill','charge','advance','adjustment') NOT NULL,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `payment_allocations_payment_id_foreign` (`payment_id`),
  KEY `payment_allocations_bill_id_foreign` (`bill_id`),
  KEY `payment_allocations_charge_id_foreign` (`charge_id`),
  KEY `payment_allocations_status_id_foreign` (`status_id`),
  CONSTRAINT `payment_allocations_bill_id_foreign` FOREIGN KEY (`bill_id`) REFERENCES `water_bills` (`id`),
  CONSTRAINT `payment_allocations_charge_id_foreign` FOREIGN KEY (`charge_id`) REFERENCES `customer_charges` (`id`),
  CONSTRAINT `payment_allocations_payment_id_foreign` FOREIGN KEY (`payment_id`) REFERENCES `payments` (`id`),
  CONSTRAINT `payment_allocations_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ledger_sources` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` varchar(50) NOT NULL,
  `table_name` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ledger_sources_type_unique` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `customer_ledgers` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` bigint(20) UNSIGNED NOT NULL,
  `transaction_date` date NOT NULL,
  `source_type_id` bigint(20) UNSIGNED NOT NULL,
  `source_id` bigint(20) UNSIGNED NOT NULL,
  `source_reference` varchar(50) DEFAULT NULL,
  `debit` decimal(12,2) NOT NULL DEFAULT 0.00,
  `credit` decimal(12,2) NOT NULL DEFAULT 0.00,
  `balance` decimal(12,2) NOT NULL DEFAULT 0.00,
  `description` text,
  `user_id` bigint(20) UNSIGNED DEFAULT NULL,
  `status_id` bigint(20) UNSIGNED DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `customer_ledgers_customer_id_foreign` (`customer_id`),
  KEY `customer_ledgers_source_type_id_foreign` (`source_type_id`),
  KEY `customer_ledgers_user_id_foreign` (`user_id`),
  KEY `customer_ledgers_status_id_foreign` (`status_id`),
  CONSTRAINT `customer_ledgers_customer_id_foreign` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`),
  CONSTRAINT `customer_ledgers_source_type_id_foreign` FOREIGN KEY (`source_type_id`) REFERENCES `ledger_sources` (`id`),
  CONSTRAINT `customer_ledgers_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`),
  CONSTRAINT `customer_ledgers_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 12. Audit Log
CREATE TABLE `audit_logs` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `table_name` varchar(50) NOT NULL,
  `record_id` bigint(20) UNSIGNED NOT NULL,
  `action` varchar(20) NOT NULL,
  `old_values` json DEFAULT NULL,
  `new_values` json DEFAULT NULL,
  `user_id` bigint(20) UNSIGNED DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `audit_logs_user_id_foreign` (`user_id`),
  CONSTRAINT `audit_logs_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 13. Laravel Cache Table
CREATE TABLE `cache` (
    `key` varchar(255) NOT NULL,
    `value` mediumtext NOT NULL,
    `expiration` int(11) NOT NULL,
    PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 14. Seed Data (Essential Lookups)
INSERT INTO `statuses` (`id`, `name`, `description`) VALUES
(1, 'Active', 'Record is active'),
(2, 'Inactive', 'Record is inactive'),
(3, 'Pending', 'Awaiting approval or action'),
(4, 'Archived', 'Record is archived'),
(5, 'Disconnected', 'Service is disconnected');

INSERT INTO `user_types` (`id`, `code`, `name`) VALUES
(1, 'ADMIN', 'Administrator'),
(2, 'STAFF', 'Staff'),
(3, 'READER', 'Meter Reader'),
(4, 'COLLECTOR', 'Collector');

INSERT INTO `ledger_sources` (`id`, `type`, `table_name`) VALUES
(1, 'BILL', 'water_bills'),
(2, 'PAYMENT', 'payments'),
(3, 'ADJUSTMENT', 'bill_adjustments'),
(4, 'CHARGE', 'customer_charges');

SET FOREIGN_KEY_CHECKS=1;
